baseurl = "https://t.yihui.org/"
title = "Yihui's Social Feeds"
author = "Yihui Xie"
languagecode = "en"
theme = "hugo-xmin"
rssLimit = 30

[pagination]
  pagerSize = 10

[permalinks]
  post = "/post/:year/:month/:day/"

[params]
  sitename = "Yihui's Social Feeds"

[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url  = "/about/"
    weight = 2
[[menu.main]]
    name = "Blogdown"
    url  = "https://github.com/rstudio/blogdown"
    weight = 3
[[menu.main]]
    name = "RSS"
    url  = "/index.xml"
    weight = 4
[[menu.main]]
    name = "Yihui's Homepage"
    url  = "https://yihui.org"
    weight = 5
[[menu.main]]
    name = "Github"
    url  = "https://github.com/yihui/social-blogdown"
    weight = 6

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      hardWraps = true
    [markup.goldmark.extensions]
      linkify = false
