on:
  workflow_dispatch:
  schedule:
    - cron:  '0 12 * * 0'
name: social-blogdown

jobs:
  fetch-messages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@HEAD
      - uses: r-lib/actions/setup-r@HEAD
      - name: Cache R packages
        uses: actions/cache@HEAD
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-
      - name: Fetch Messages
        run: |
          Rscript R/fetch.R
      - name: Push results
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add --all *
          git commit -m "Weekly update" && git push || true
